### ISSUE TITLE
Issue with Blood Lords Premium Module

### ISSUE THREAD

**Issue by Craftzero** [mclemente/fvtt-advanced-macros#50]
The PF2e Premium Modules Blood Lords use a handful of Macros for various things (changing the landing  page, activating ambience, etc).  With Advanced Macros active, these macros don't seem to work.  Here is the error:

[localhost-1669155632195.log](https://github.com/League-of-Foundry-Developers/fvtt-advanced-macros/files/10071500/localhost-1669155632195.log)

**Comment by mclemente** [comment]
Hm, I know what's causing this but I don't understand why it is happening, unless Blood Lords replaces/wraps `TextEditor._createContentLink`.
That said, I can fix the error breaking macro execution, but I can't guarantee macros like it will run with arguments. They will run, but not with arguments. I doubt any of them have arguments, though, since that's a recent change from Advanced Macros.
Do the macros have spaces on their names? That might by it.
I've released a new version that might fix the issue.

**Comment by Craftzero** [comment]
All the macros that appear broken do in fact have spaces in the titles!

**Comment by mclemente** [comment]
Hey, was this issue resolved with the changes on v1.19.3? I can't test stuff from premium content on my own.

**Comment by mclemente** [comment]
Foundry V11 will overhaul how macro calls are made, but this was an issue related to its journal feature, so I'm wondering if it is still broken on V11.
