### ISSUE TITLE
Passing object argument does not work any more in v11

### ISSUE THREAD

**Issue by KristjanLaane** [mclemente/fvtt-advanced-macros#70]
Calling a macro with an argument like so used to work for me in v10:
`macro.execute(item5e)`

Now in v11.302 I’m getting an error inside the macro on the very first line just with this:
`if (!args) return`

The error:
> VM287868:4 Uncaught (in promise) ReferenceError: undefined. args is not defined
> [Detected 3 packages: advanced-macros, lib-wrapper, rngd]
>     at Macro.eval (eval at #executeScript (foundry.js:22632:16), <anonymous>:4:13)
>     at #executeScript (foundry.js:22636:17)
>     at Macro.execute (foundry.js:22584:35)

**Comment by mclemente** [comment]
Arguments are not an Advanced Macros feature on Foundry V11, that became a core feature and the implementation is different from what Advanced Macros used to:
- The arguments are passed as part of an object now.
  - E.g. `macro.execute(item5e)` -> `macro.execute({item5e})`.
- The macros are to be written assuming the parameter will be passed as an individual parameter instead of part of `args`.
  - E.g. `if (!args) return` -. `if (!item5e) return`.

I don't intend on fixing macros broken by V11 changes, look for more help on #macro-polo channel on Foundry's discord.

**Comment by KristjanLaane** [comment]
Thank you very much! I got access to the item5e parameter within the macro very nicely now with your guidance. 

When I set the same macro to Execute for Specific User then the macro does not run though - no console logs and no error messages or warnings for GM or player user, just nothing happens. That is a separate issue though.

**Comment by mclemente** [comment]
Hm, can you open another issue and share the entire macro? Just export the macro's data and upload it to the issue.
